# Form implementation generated from reading ui file 'loginWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_loginWindow(object):
    def setupUi(self, loginWindow):
        loginWindow.setObjectName("loginWindow")
        loginWindow.resize(400, 709)
        self.label_5 = QtWidgets.QLabel(parent=loginWindow)
        self.label_5.setGeometry(QtCore.QRect(-10, -10, 441, 291))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("image/img7.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(parent=loginWindow)
        self.label.setGeometry(QtCore.QRect(0, 230, 401, 481))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
" border: none;\n"
"            border-radius: 20px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(parent=loginWindow)
        self.label_3.setGeometry(QtCore.QRect(60, 270, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(20, 107, 30);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=loginWindow)
        self.label_4.setGeometry(QtCore.QRect(100, 330, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(180, 180, 180);")
        self.label_4.setObjectName("label_4")
        self.input_username = QtWidgets.QLineEdit(parent=loginWindow)
        self.input_username.setGeometry(QtCore.QRect(20, 400, 361, 71))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.input_username.setFont(font)
        self.input_username.setStyleSheet("QLineEdit{   \n"
"              width: 100%;\n"
"            padding: 10px;\n"
"            margin: 10px 0;\n"
"            border: none;\n"
"            border-radius: 10px;\n"
"            outline: none;\n"
"            font-size: 16px;\n"
"            background-color: #f2f6f2;\n"
"            color: rgb(0, 85, 0);}\n"
"QLineEdit:focus {\n"
"                border: 2px solid rgb(20, 107, 30);\n"
"            }\n"
"\n"
"\n"
"")
        self.input_username.setObjectName("input_username")
        self.input_password = QtWidgets.QLineEdit(parent=loginWindow)
        self.input_password.setGeometry(QtCore.QRect(20, 470, 361, 71))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.input_password.setFont(font)
        self.input_password.setStyleSheet("QLineEdit{   \n"
"              width: 100%;\n"
"            padding: 10px;\n"
"            margin: 10px 0;\n"
"            border: none;\n"
"            border-radius: 10px;\n"
"            outline: none;\n"
"            font-size: 16px;\n"
"            background-color: #f2f6f2;\n"
"            color: rgb(0, 85, 0);}\n"
"QLineEdit:focus {\n"
"                border: 2px solid rgb(20, 107, 30);\n"
"            }\n"
"\n"
"\n"
"")
        self.input_password.setObjectName("input_password")
        self.loginbutton = QtWidgets.QPushButton(parent=loginWindow)
        self.loginbutton.setGeometry(QtCore.QRect(20, 570, 361, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.loginbutton.setFont(font)
        self.loginbutton.setStyleSheet("\n"
"QPushButton {\n"
"               width: 100%;\n"
"            padding: 10px;\n"
"            border: none;\n"
"background-color: rgb(20, 107, 30);\n"
"            border-radius: 30px;\n"
"            color: white;\n"
"            font-size: 25px;\n"
"            transition: background-color 0.3s;\n"
"            }\n"
"QPushButton:hover {\n"
"background-color: rgb(0, 85, 0);\n"
"\n"
"            }\n"
"")
        self.loginbutton.setObjectName("loginbutton")
        self.label_6 = QtWidgets.QLabel(parent=loginWindow)
        self.label_6.setGeometry(QtCore.QRect(60, 650, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(180, 180, 180);")
        self.label_6.setObjectName("label_6")
        self.createbutton = QtWidgets.QPushButton(parent=loginWindow)
        self.createbutton.setGeometry(QtCore.QRect(230, 650, 131, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(9)
        self.createbutton.setFont(font)
        self.createbutton.setStyleSheet("color: rgb(20, 107, 30);\n"
"background-color:none;\n"
"border: none;\n"
"font: 75 16pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;\n"
"")
        self.createbutton.setObjectName("createbutton")
        self.back_button = QtWidgets.QPushButton(parent=loginWindow)
        self.back_button.setGeometry(QtCore.QRect(10, 20, 31, 31))
        self.back_button.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"            width: 50px;\n"
"            height:50px;\n"
"            border: none;\n"
"            background-color: #f2f6f2;\n"
"            border-radius: 50%;\n"
"            cursor:pointer;          \n"
"  }\n"
"QPushButton:hover {\n"
"\n"
"background-color: rgb(224, 227, 224);\n"
"\n"
"            }\n"
"")
        self.back_button.setText("")
        self.back_button.setObjectName("back_button")
        self.label_2 = QtWidgets.QLabel(parent=loginWindow)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 31, 31))
        self.label_2.setStyleSheet("background-color: #f2f6f2;")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("image/left.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(loginWindow)
        QtCore.QMetaObject.connectSlotsByName(loginWindow)

    def retranslateUi(self, loginWindow):
        _translate = QtCore.QCoreApplication.translate
        loginWindow.setWindowTitle(_translate("loginWindow", "Welcome Back"))
        self.label_3.setText(_translate("loginWindow", "Welcome Back"))
        self.label_4.setText(_translate("loginWindow", "Login to your account"))
        self.input_username.setPlaceholderText(_translate("loginWindow", "Full Name"))
        self.input_password.setPlaceholderText(_translate("loginWindow", "Password"))
        self.loginbutton.setText(_translate("loginWindow", "Login"))
        self.label_6.setText(_translate("loginWindow", "Don’t have account ?"))
        self.createbutton.setText(_translate("loginWindow", "Sign up"))
