# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(397, 710)
        self.label = QtWidgets.QLabel(parent=mainWindow)
        self.label.setGeometry(QtCore.QRect(0, 0, 401, 711))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("image/img6.jpg"))
        self.label.setScaledContents(True)
        self.label.setIndent(-1)
        self.label.setOpenExternalLinks(False)
        self.label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByKeyboard)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=mainWindow)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 271, 81))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=mainWindow)
        self.label_3.setGeometry(QtCore.QRect(30, 180, 321, 81))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=mainWindow)
        self.label_4.setGeometry(QtCore.QRect(30, 110, 271, 91))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.login_button = QtWidgets.QPushButton(parent=mainWindow)
        self.login_button.setGeometry(QtCore.QRect(50, 480, 301, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.login_button.setFont(font)
        self.login_button.setStyleSheet("\n"
"QPushButton {\n"
"               width: 100%;\n"
"            padding: 10px;\n"
"            background-color: none;\n"
"            border: none;\n"
"            border-radius: 20px;\n"
"            color: white;\n"
"            font-size: 25px;\n"
"            transition: background-color 0.3s;\n"
"            }\n"
"QPushButton:hover {\n"
"                border-radius: 20px;\n"
"background-color: rgb(231, 231, 231);\n"
"            }\n"
"")
        self.login_button.setObjectName("login_button")
        self.create_button = QtWidgets.QPushButton(parent=mainWindow)
        self.create_button.setGeometry(QtCore.QRect(60, 530, 301, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.create_button.setFont(font)
        self.create_button.setStyleSheet("\n"
"QPushButton {\n"
"               width: 100%;\n"
"            padding: 10px;\n"
"            background-color: none;\n"
"            border: none;\n"
"            border-radius: 20px;\n"
"            color: white;\n"
"            font-size: 25px;\n"
"            transition: background-color 0.3s;\n"
"            }\n"
"QPushButton:hover {\n"
"                border-radius: 20px;\n"
"background-color: rgb(231, 231, 231);\n"
"            }\n"
"")
        self.create_button.setObjectName("create_button")

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Mian Window"))
        self.label_2.setText(_translate("mainWindow", "The best "))
        self.label_3.setText(_translate("mainWindow", "your plants"))
        self.label_4.setText(_translate("mainWindow", "app for"))
        self.login_button.setText(_translate("mainWindow", "Sign in"))
        self.create_button.setText(_translate("mainWindow", "Create an account"))
